# Generated by Django 4.1.5 on 2023-02-09 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phrases',
            name='image',
        ),
    ]
